name: Deploy to WordPress.org
on:
  push:
    tags-ignore:
    - 'v*-alpha*'
    - 'v*-beta*'
    - 'v*-rc*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: simple-html-rich-text-for-block-editor